name: Build Android
run-name: Creating Production Ready Android App 🚀
on:
  push:
    branches:
      - android

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: android

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Navigate to frontend folder and install dependencies
        run: cd frontend && npm ci

      - name: Check if the folder content
        run: ls
